# Generated by Django 4.2.5 on 2023-09-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('short_name', models.CharField(max_length=250, verbose_name='Short name')),
                ('icon_uri', models.CharField(max_length=250, verbose_name='Icon uri')),
                ('data', models.JSONField(verbose_name='Data')),
            ],
        ),
    ]
